services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
